#!/bin/bash
printf "\n"
printf " * ArkOS Documentation:          https://github.com/christianhaitian/arkos/wiki\n"
printf " * Debian Reference:             https://www.debian.org/doc/manuals/debian-reference/index.en.html\n"
printf "\n"
